name: Set up VapourSynth
description: Build and install VapourSynth
inputs:
  vapoursynth-version:
    description: VapourSynth version
    required: true
runs:
  using: composite
  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
      with:
        key: vapoursynth-${{ inputs.vapoursynth-version }}

    - name: Checkout zimg
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: sekrit-twc/zimg
        path: zimg
        submodules: recursive

    - name: Install zimg
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        popd
        rm -rf zimg

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.14.3

    - name: Install uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1

    - name: Install Python dependencies
      shell: bash
      run: uv pip install --system -U cython

    - name: Checkout VapourSynth
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: vapoursynth/vapoursynth
        ref: R${{ inputs.vapoursynth-version }}
        path: vapoursynth

    - name: Install VapourSynth
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        sudo mkdir -p /usr/lib/vapoursynth
        popd
        rm -rf vapoursynth
