name: Set up VapourSynth
description: Build and install VapourSynth
inputs:
  vapoursynth-version:
    description: VapourSynth version
    required: true
runs:
  using: composite
  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2.18
      with:
        key: vapoursynth-${{ inputs.vapoursynth-version }}

    - name: Checkout zimg
      uses: actions/checkout@v4.2.2
      with:
        repository: sekrit-twc/zimg
        path: zimg
        submodules: recursive

    - name: Install zimg
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        popd
        rm -rf zimg

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.12

    - name: Install uv
      uses: astral-sh/setup-uv@v6.0.1

    - name: Install Python dependencies
      shell: bash
      run: uv pip install --system -U cython

    - name: Checkout VapourSynth
      uses: actions/checkout@v4.2.2
      with:
        repository: vapoursynth/vapoursynth
        ref: R${{ inputs.vapoursynth-version }}
        path: vapoursynth

    - name: Install VapourSynth
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install -j$(nproc)
        sudo mkdir -p /usr/lib/vapoursynth
        popd
        rm -rf vapoursynth
